github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-application-chart
      useSinglePullRequest: true
    repositories:
    - name: activiti-cloud-full-chart
      useSinglePullRequest: true
