dependencies:
- alias: auditpostgresql
  name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.11.0
  condition: application.activiti-cloud-audit.db.deployPostgres,activiti-cloud-audit.db.deployPostgres,db.deployPostgres
