# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

global:
  rabbitmq:
    host:
      value: ""
    username:
      value: guest
    password:
      value: guest
  keycloak:
    url: ""
    name: keycloak
    service:
      type: http
      port: 80

db:
  uri: ""
  name: auditpostgresql
  password: audit
  deployPostgres: false
  port: 5432
  generateDdl: "true"
  ddlAuto: update

auditpostgresql:
   postgresPassword: audit

javaOpts:
  xmx: 512m
  xms: 512m
  other: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90

image:
  repository: activiti/activiti-cloud-audit
  tag: 7.0.0.Beta3
  pullPolicy: IfNotPresent
service:
  name: audit
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "false"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    memory: 768Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 140
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 4
readinessProbe:
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
terminationGracePeriodSeconds: 20

## Allows the specification of additional environment variables
extraEnv: |
  # - name: ACT_KEYCLOAK_URL
  #   valueFrom:
  #     configMapKeyRef:
  #       name: {{ .Release.Name }}-keycloak-http
  #       key: expose-keycloak-service-key

ingress:
  ## Set to true to enable ingress record generation
  enabled: false